name: school_track
publish_to: 'none'
description: School transport management MVP - Firebase ready.
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.3
  firebase_messaging: ^16.0.3
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1

flutter:
  uses-material-design: true
